name: publish

on:
  push:
    branches: [pypi]

jobs:
  pypi:
    environment: PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.4
        with:
          virtualenvs-in-project: true

      - name: Load dependency cache
        id: dependency-cache
        uses: actions/cache@v2
        with:
          path: .venv/
          key: venv-${{ runner.os }}-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies
        if: steps.dependency-cache.outputs.cache-hit != 'true'
        run: poetry install --no-interaction

      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.API_TOKEN_TEST }}
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.testpypi "${POETRY_PYPI_TOKEN_PYPI}"
          poetry publish --build -r testpypi --no-interaction
